#!/usr/bin/env python3
"""
select.py - record the director's choice of take for a shot.

    python3 tools/select.py --project projects/the-woman-beyond-the-hill --shot 6 --take 3
    python3 tools/select.py --project ... --shot 6 --take 3 --note "lamp gutters on 4"
    python3 tools/select.py --project ... --list
    python3 tools/select.py --project ... --missing
    python3 tools/select.py --project ... --shot 6 --clear

Copies the chosen take into selects/ and records it in selects.json.

This tool does not score, rank, recommend or auto-select. It has no opinion
about which take is better. It copies the take you name and writes down that
you named it. The director chooses.

Idempotent: selecting the same take twice is a no-op. Selecting a different
take for a shot replaces the previous choice and says so.
"""

import argparse
import hashlib
import json
import os
import shutil
import sys
from datetime import datetime, timezone


def sha(path, limit=4 << 20):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(1 << 20):
            h.update(chunk)
            limit -= len(chunk)
            if limit <= 0:
                break
    return h.hexdigest()[:16]


def load(p):
    if os.path.exists(p):
        with open(p) as f:
            return json.load(f)
    return {"project": None, "selections": {}}


def save(p, data):
    tmp = p + ".tmp"
    with open(tmp, "w") as f:
        json.dump(data, f, indent=2, sort_keys=True)
    os.replace(tmp, p)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--shot", type=int)
    ap.add_argument("--take", type=int)
    ap.add_argument("--note", default="")
    ap.add_argument("--clear", action="store_true", help="unselect this shot")
    ap.add_argument("--list", action="store_true", help="show all selections")
    ap.add_argument("--missing", action="store_true", help="show unselected shots")
    args = ap.parse_args()

    takes_dir = os.path.join(args.project, "takes")
    sel_dir = os.path.join(args.project, "selects")
    sel_json = os.path.join(args.project, "selects.json")
    shotlist = os.path.join(args.project, "shotlist.json")

    with open(shotlist) as f:
        spec = json.load(f)
    ids = [s["id"] for s in spec["shots"]]
    ffmpeg_only = {28}

    os.makedirs(sel_dir, exist_ok=True)
    data = load(sel_json)
    data["project"] = spec.get("project")

    if args.list:
        if not data["selections"]:
            print("no selections yet")
            return
        print(f"{len(data['selections'])} selection(s):\n")
        for sid in sorted(data["selections"], key=int):
            s = data["selections"][sid]
            note = f"   {s['note']}" if s.get("note") else ""
            print(f"  shot {int(sid):02d}  take {s['take']}   {s['selected_at'][:16]}{note}")
        return

    if args.missing:
        chosen = {int(k) for k in data["selections"]}
        gaps = [i for i in ids if i not in chosen and i not in ffmpeg_only]
        if not gaps:
            print("every shot has a selection (28 is ffmpeg-only)")
            return
        print(f"{len(gaps)} shot(s) without a selection:")
        print("  " + ", ".join(str(i) for i in gaps))
        return

    if args.shot is None:
        sys.exit("need --shot (with --take), or --list / --missing")
    if args.shot not in ids:
        sys.exit(f"no shot {args.shot} in shotlist")

    key = str(args.shot)

    if args.clear:
        prev = data["selections"].pop(key, None)
        if not prev:
            print(f"shot {args.shot:02d}: nothing selected, nothing to clear")
            return
        dest = os.path.join(sel_dir, prev["file"])
        if os.path.exists(dest):
            os.remove(dest)
        save(sel_json, data)
        print(f"shot {args.shot:02d}: cleared (was take {prev['take']})")
        return

    if args.shot in ffmpeg_only:
        sys.exit(f"shot {args.shot} is pure black and is generated by ffmpeg in "
                 f"assemble.py. There is nothing to select.")
    if args.take is None:
        sys.exit("need --take")

    src = os.path.join(takes_dir, f"shot-{args.shot:02d}-take-{args.take}.mp4")
    if not os.path.exists(src):
        have = sorted(f for f in os.listdir(takes_dir)
                      if f.startswith(f"shot-{args.shot:02d}-take-")) \
            if os.path.isdir(takes_dir) else []
        msg = f"no such take: {os.path.basename(src)}"
        if have:
            msg += "\navailable: " + ", ".join(h.split("take-")[1][:-4] for h in have)
        sys.exit(msg)

    fname = f"shot-{args.shot:02d}.mp4"
    dest = os.path.join(sel_dir, fname)
    prev = data["selections"].get(key)

    if prev and prev["take"] == args.take and os.path.exists(dest):
        print(f"shot {args.shot:02d}: take {args.take} already selected, no change")
        return

    tmp = dest + ".tmp"
    shutil.copy2(src, tmp)
    os.replace(tmp, dest)

    data["selections"][key] = {
        "shot": args.shot,
        "take": args.take,
        "source": os.path.basename(src),
        "file": fname,
        "sha256_prefix": sha(dest),
        "selected_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "note": args.note,
    }
    save(sel_json, data)

    if prev:
        print(f"shot {args.shot:02d}: take {prev['take']} -> take {args.take} (replaced)")
    else:
        print(f"shot {args.shot:02d}: take {args.take} selected")
    print(f"  {src}\n  -> {dest}")

    chosen = {int(k) for k in data["selections"]}
    gaps = [i for i in ids if i not in chosen and i not in ffmpeg_only]
    print(f"  {len(chosen)}/{len(ids) - len(ffmpeg_only)} shots selected"
          + (f", {len(gaps)} to go" if gaps else " — all selected"))
    print("\nnext: crop.py (2.39:1 + grain), then assemble.py")


if __name__ == "__main__":
    main()
